name=input("enter your full name:")
phone_number=input("enter your phone number")
#result=len(name)
#result=name.find("h")
#result=name.rfind("q")
#result=name.capitalize("h")
#name=name.upper()
#name=name.lower()
#result=name.isdigit()
#result=name.isalpha()
#result=phone_number.count("-")
phone_number=phone_number.replace("-","")
print(phone_number)
#print(help(str))